# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - feature
  - main

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: CIPractise
    displayName: Build
    pool: 'Default'
    steps:

    - script: |
        sudo apt-get update && sudo apt-get install -y maven
        mvn clean install
      displayName: 'Maven build'
    - task: DockerInstaller@0
      inputs:
       dockerVersion: 17.09.0-ce
       releaseType: stable
       
    - script: |
        sudo systemctl daemon-reload
        sudo systemctl status docker
        sudo systemctl restart docker
        sudo systemctl status docker
        sudo chmod 666 /var/run/docker.sock
      displayName: 'Docker Setup'
     
      

    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        containerRegistry: 'DockerRegistry'
        command: 'login'

    - task: Docker@2
      inputs:
        containerRegistry: 'DockerRegistry'
        repository: 'riaoct30/tomcat-test'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          ${tag}
      retryCountOnTaskFailure: '1'

   