# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - feature
  - main

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPackageAndPush
  displayName: Pipeline
  jobs:
  - job: CIPractise
    displayName: Build
    pool:
      vmImage: ubuntu-latest

    steps:

    
    # - script: |
    #     sudo apt-get update && sudo apt-get install -y maven
    #     mvn clean install
    #   displayName: 'Maven build'
    
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        goals: 'package'

    - task: DockerInstaller@0
      inputs:
       dockerVersion: 17.09.0-ce
       releaseType: stable
  

    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        containerRegistry: 'DockerRegistry'
        command: 'login'

    - task: Docker@2
      inputs:
        containerRegistry: 'DockerRegistry'
        repository: 'riaoct30/tomcat-test'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(tag)'
      retryCountOnTaskFailure: '1'